### ISSUE TITLE
[Bug]: Multiple UI issues with F-droid build

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/Butterfly#158]
### What happened?

- [x] 1. Drawing with multiple fingers leave multiple trails. But using "undo" makes inconsistent changes, sometimes restoring "undone" strikes back. Sometimes after undo it shows fake transient state of the scene which immediately jumps to other state as soon as I pan, zoom or edit the scene further.
- [x] 2. Sometimes after zooming in or out using pinch gesture it switches from panning tool to drawing tool (i.e. the previous tool).
- [x] 3. Sometimes after zooming in or out it displays pixelated, low-quality zoom result. This is OK while the zoom action is ongoing, but I expect Butterfly to redraw the scene after zoom is completed. Sometimes it also results in a cropped image (the crop disappears on any scene redraw).
- [x] 4. Cannot undo the action of Path Eraser.
- [x] 5. Text added using text tool only briefly appears, then immediately disappears.
- [x] 6. I discovered the "Insert / Layers / Areas / ..." menu almost by accident. Single tap when in panning mode at empty canvas space may be too unintuitive.
- [x] 7. Opening a popup (i.e. layer or area), then leaving it clears the scene.
- [x] 8. Adding "Layer" tool using "+" item, then trying to delete it with a delete button leads to "Are you sure? Do you really want to delete this item? [No] [Yes]" dialogue, but "yes" button does not work (taps are ignored by the application), only "no".
- [x] 9. Try drawing two circles - big and small, one inside another. Then try to use Path Eraser tool to delete only the small circle. It removes both instead.
- [x] 10. There are layers and layer tool.  It asks for "Name" and "Layer", but it is not clear (at least without reading the documentation) how to move paths between layers and how to toggle layer visibility.

### Version

1.3.0-beta.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Are you sure you use the 1.3.0-beta.1? On fdroid, it semes to have an outdated version https://f-droid.org/de/packages/dev.linwood.butterfly/

But I can look if I find these issue in the latest version

**Comment by vi** [comment]
Opening the app, tapping a button at the top left, choosing "Settings", then "Data",  then tapping the back button at the top, then "Information" (another bug by the way: this item is missing when Settings menu is opened initially) shows the following popup: "Butterfly 1.3.0-beta.1 [Copy version] [view licenses] [close]".

Android app info also shows "version 1.3.0-beta.1".

F-Droid page (within app, not on the website) for Linwood Butterfly shows "Updated today" and "NEW IN VERSION 1.3.0-BETA.1: Added custom designs, ..."

**Comment by CodeDoctorDE** [comment]
Oh okay thanks. Thank you for this detailed report. I tested this build and found no bug report, so I declared it as beta.

1. ✔️ 
2. ❌ 
3. ✔️ 
4. ✔️ 
5. ❌ 
6. Do you have a good idea how I could make it better? I don't want to waste too much space on the screen
7. ❌ 
8. ✔️ (On all painters)
9.✔️  (Yeah I rebuilt the collsion system to have a box collider. It should have a better performance. Should I reimplement the exact shape?)
10.  Name is the name of the painter, the Layer is the layer that will be applied when clicking on the element

**Comment by CodeDoctorDE** [comment]
Can you please test <https://preview.butterfly.linwood.dev>?

**Comment by CodeDoctorDE** [comment]
![image](https://user-images.githubusercontent.com/20452814/166304638-888be6f7-6b16-4b87-8f95-748ab833e219.png)
What do you think when adding the insert dialog in the + icon? Then you can add painters in the same dialog as inserting images

**Comment by vi** [comment]
> Can you please test https://preview.butterfly.linwood.dev?

Is there a pre-built Android version of it?

**Comment by vi** [comment]
> I tested this build and found no bug report, so I declared it as beta.

Have you tried using Android version of the app for some real-world note taking? For example, drawing a task board with backlog, in progress, done, tested columns for further Butterfly development? Or to draw and edit some simple art.

The bugs are plentiful are encountered very quickly when I try to use Butterfly, creating feeling that developer did not try to actually use the app, only checked that it builds and runs.

**Comment by vi** [comment]
> Can you please test https://preview.butterfly.linwood.dev?

Trying it.

1. No tooltips for tools, only for "Hand" or "Create".
2. Path eraser tool has intuitive icon (it looks like some path creator instead). This is exacerbated by the missing tooltip. Proper icon may be based on eraser tool's icon, but also with a path (i.e. a curvy line) superimposed.
    It erases excessive amount of content (like on Android version). What does "stroke width" mean for a path eraser tool by the way? I expect it to be able to work with zero stroke width.
4. Sometimes a path disappears when I just select other tool. Maybe it is absent from the scene and only continues to be visible intermittently.
5. Sometimes "undo" removes both recent brush stroke and some other old element (e.g. a text).
6. Layers are still very unintuitive.
    > Name is the name of the painter, the Layer is the layer that will be applied when clicking on the element

    Read, but not understood. Typically I expect layers to work like in other raster and vector graphics editors: there is a stack of layers, one of the layers is active (so newly added elements are assigned to that level), there are visibility toggles for each layer, layers can be reordered (e.g. by dragging), layers can be removed (which removes all their elements). Typically there are little preview icons for each layer.
    Where is the list of layers in Butterfly?

7. When I move element (click, then select "Move"), there is no visual indication that the next click will move element. I expect some UI change. A move crossarrows icon may be positioned near element that is being moved. The element may be even animated (e.g. Apple-style shaking). The same for "Duplicate" action.
8. No preview when I adjusting the text size. I need to close the text edit window every time to see if the text size is right.
9. Selecting items show additional menu to choose which nearby element you want to select too often. Seems like only bounding box is considered, not the actual shape of the path. Typically only icon is displayed, without any mini-preview of that element in isolation.
10. In selection refinement menu you need to click "OK" every time to confirm selection, which is an extra unnecessary click. Also it is cumbersome to do multiple actions with the same element. For example, to duplicate, then edit a text element, I need 10 mouse clicks.
11. There seems to be no way to select multiple elements (e.g. to place them all on one layer).
12. It bothers to ask confirmation before deleting an element from scene. Is should not be really needed, since deletion can be reverted with "Undo" anyway.
13. "Area" tool settings's window is named "Eraser".
14. Clicking within area when area tool is active sometimes offers to enter or delete the are, but sometimes clicks are ignored.

Non-reproduced bugs:

1. Path eraser actions are undoable.
2. Text does not get invisible immediately.
3. Zooming in and out using mouse now feels much better compared to what was before.

---

Overall quality of the linked web version feels much better compared to Android app's one, though still not "beta". UI/UX is the main sore point. 

---

What does "Include eraser?" setting mean for hand and some other tools? I haven't found it affecting anything.

What are "areas"? I created an area, entered it, added a brush stroke, exited the area, then deleted the area. I expected the brush stroke to disappear (thinking areas are just groups from other vector editors, but with other name), but it remained.

**Comment by CodeDoctorDE** [comment]
1. The name property on all painters sets the tooltip. No other reason has the name property. I can add the painter name as default.
2. If you have a better icon you can share it. Here is the icon library I'm using: https://phosphoricons.com/. Yeah, it's this box collider shape that's so big. I search for a way to calculate the hit box without any lag.
3. It gets only removed if you don't finish the line by removing your hand/input from the display.
4. I cannot reproduce it. Can you give more details?
5. Name has nothing to do with the assigned layer (see point 1). Layers can be reached with a click on an empty canvas spot (like the insert dialog).
6. Yeah, I'm currently working on it
7. Yeah, it's only updated when clicking the okay button. I will fix it.
8. See point 2. Currently there is no multi editing of elements. You can assign layers quickly with the layer painter.
9. Should this menu be opened after doing the actions?
10. See point 8
11. I had added it before undo/redo was added. I will remove it in the next release
12. I'm working on it
13. You can enter an area to restrict your viewport. When you are entering an area you can exit them using this button. Currently I cannot replicate that clicks are ignored
14. I see the issue. I forgot the update the ui after clicking on it. I'm working on it
15. It shouldn't. Technically the selection list cannot have the same elements (it's a `Set`, they can only have unique elements). Maybe there are multiple elements on the same position?
16. I'm working on it.
17. Okay, this can be an issue. I will restrict the selection.
18. That's right. Circle and triangles are also useful
19. Thanks! Will be fixed

> What does "Include eraser?"

The note taking app is based on vector operations. Technically you add an element when erasing content. With this option you can select the eraser element to remove them (or moving).

> What are "areas"?

Areas are a way to restrict the viewport (for example to export them). They don't interact with elements and only restrict a size (not elements). If you want to remove the area, nothing should be deleted (because they don't group elements only restrict the viewport).

Thanks for giving me feedback. I'm currently working alone on this project and making my german "Abitur". I cannot give the same quality as big tech companies or teams that are working together on a project. I'm testing it while developing it but many bugs can happen while fixing others. Betas means that there are no major breaking changes but they can be bugs. For me it's important that users can test it before releasing it to the public.

**Comment by CodeDoctorDE** [comment]
Hi, I added some improvements. Can you try it? The selection dialog is rewritten, some bugs are fixed and a move indicator was added

**Comment by Lokawn** [comment]
> Can you please test https://preview.butterfly.linwood.dev?

In the f-droid version, the lines remain smooth while writing but as soon as the stylus is lifted they become pixelated (don't know the correct word). 
But the lines are smooth in the web version.

https://user-images.githubusercontent.com/39772448/166953688-6a0b38cc-cfc2-4be4-b2aa-ef5ba842330d.mp4

**Comment by CodeDoctorDE** [comment]
Can you try the current build? https://github.com/LinwoodCloud/Butterfly/actions/runs/2274565702

**Comment by vi** [comment]
I'll re-test later (someday) both, maybe recording a video with my comments.

**Comment by Lokawn** [comment]
> Can you try the current build? https://github.com/LinwoodCloud/Butterfly/actions/runs/2274565702

I tested the new build, the app is unusable as the strokes are appearing on screen after some delay,  I encountered the same problem with [xournal_pp mobile](https://gitlab.com/TheOneWithTheBraid/xournalpp_mobile/), but apps like Noteshelf and Inkredible work fine.

**Comment by CodeDoctorDE** [comment]
Is this bug appears in the latest nightly version too?
On my linux and android device, it works. Do you try the portable version on linux?
Xournal_pp mobile and butterfly uses both flutter.

**Comment by Lokawn** [comment]
I was referring to the latest nightly which you have linked above.

**Comment by CodeDoctorDE** [comment]
Yes I know. Can you reproduce it in the latest beta?
Maybe it will happen in the beta too.

**Comment by Lokawn** [comment]
I cannot reproduce it in the latest beta present on Fdroid (v1.3.0-beta.1)
I am uploading two videos, first one is from  version linked above and second from Fdroid build, you can appreciate the difference.
Notice as I start writing 'lite ' in the second video, the tablet UI is not showing any unresponsiveness.

https://user-images.githubusercontent.com/39772448/167092747-ff82bbc6-fd50-4a1a-a591-781d83169918.mp4



https://user-images.githubusercontent.com/39772448/167092237-617221f6-b517-4763-928a-afd76499ecfc.mp4

**Comment by CodeDoctorDE** [comment]
Thanks for reporting this issue.
It seems very laggy (for me: maybe the view will be rerendered to often?!).
I will notify you if I fixed it

**Comment by CodeDoctorDE** [comment]
Okay, it seems there is no other method than removing the autosave functionality on web.

**Comment by CodeDoctorDE** [comment]
I will release the next version in a few hours if you don't find any new bugs

**Comment by Lokawn** [comment]
> This issue has already been fixed. I will release a new version tomorrow

I downloaded the latest version from Releases section and the bug is still present.

https://user-images.githubusercontent.com/39772448/167198702-c5c5abe1-52bd-44d7-9834-566f6bd99e85.mp4

**Comment by CodeDoctorDE** [comment]
> > This issue has already been fixed. I will release a new version tomorrow
> 
> I downloaded the latest version from Releases section and the bug is still present.
> 
>  Screen_Recording_20220507-000920.mp4

Strange, I think I added the bug again after fixing the undo/redo issues

**Comment by CodeDoctorDE** [comment]
Fixed. But I don't think it's very critical
